# Generated by Django 3.2.5 on 2023-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giver_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='pic_upload/images')),
                ('giver_name', models.CharField(max_length=20)),
                ('aaddhar', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=20)),
                ('native', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('veh_type', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='taker_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='pic_upload/images')),
                ('giver_name', models.CharField(max_length=20)),
                ('aaddhar', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=20)),
                ('native', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
