# Generated by Django 3.2.5 on 2023-04-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_make_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='make_trip',
            new_name='make_trips',
        ),
    ]
