# Generated by Django 3.2.5 on 2023-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_rename_make_trip_make_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_trips',
            name='status',
            field=models.CharField(default='nul', max_length=20),
            preserve_default=False,
        ),
    ]
