# Generated by Django 3.2.5 on 2023-05-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20230501_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requested_trip',
            old_name='trip_id',
            new_name='payment_id',
        ),
        migrations.AddField(
            model_name='requested_trip',
            name='payment_status',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
