# Generated by Django 3.2.5 on 2023-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20230501_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_trip',
            name='destination',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requested_trip',
            name='start',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
